// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'counter': string;
  'minusButton': string;
  'plusButton': string;
}
export const cssExports: CssExports;
export default cssExports;
